version: '3'
services:
  service-discovery:
    container_name: service-discovery
    stdin_open: true
    build:
      context: service-discovery
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:8761/actuator/health || exit 1" ]
      interval: 20s
      timeout: 5s
      retries: 5

  configuration:
    container_name: configuration
    environment:
      - EUREKA_SERVER=http://service-discovery:8761/eureka
    stdin_open: true
    build:
      context: configuration
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:8888/actuator/health || exit 1" ]
      interval: 20s
      timeout: 5s
      retries: 5
    depends_on:
      service-discovery:
        condition: service_healthy

  api-gateway:
    container_name: api-gateway
    environment:
      - EUREKA_SERVER=http://service-discovery:8761/eureka
    stdin_open: true
    build:
      context: api-gateway
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      service-discovery:
        condition: service_healthy

  bootiful-java1:
    container_name: java-client1
    environment:
      - SPRING_PROFILES_ACTIVE=${BOOTIFUL_JAVA_PROFILE:-local}
      - CONFIG_SERVER=http://configuration:8888
      - EUREKA_SERVER=http://service-discovery:8761/eureka
    stdin_open: true
    build:
      context: bootiful-java
      dockerfile: Dockerfile
#    ports:
#      - ${BOOTIFUL_JAVA_PORT:-8007}:8007
    depends_on:
      configuration:
        condition: service_healthy

  bootiful-java2:
    container_name: java-client2
    environment:
      - SPRING_PROFILES_ACTIVE=${BOOTIFUL_JAVA_PROFILE:-local}
      - CONFIG_SERVER=http://configuration:8888
      - EUREKA_SERVER=http://service-discovery:8761/eureka
    stdin_open: true
    build:
      context: bootiful-java
      dockerfile: Dockerfile
#    ports:
#      - 8006:8007 # ${BOOTIFUL_JAVA_PORT:-8007}:8007
    depends_on:
      configuration:
        condition: service_healthy

  bootiful-kotlin:
    container_name: kotlin-client1
    environment:
      - SPRING_PROFILES_ACTIVE=${BOOTIFUL_KOTLIN_PROFILE:-dev}
      - CONFIG_SERVER=http://configuration:8888
      - EUREKA_SERVER=http://service-discovery:8761/eureka
    stdin_open: true
    build:
      context: bootiful-kotlin
      dockerfile: Dockerfile
#    ports:
#      - ${BOOTIFUL_KOTLIN_PORT:-8008}:8008
    depends_on:
      configuration:
        condition: service_healthy


networks:
  default:
    driver: bridge