version: '3'
services:
  config-server:
    container_name: configuration
    stdin_open: true
    build:
      context: configuration
      dockerfile: Dockerfile
#      network: host
    ports:
      - 8888:8888
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:8888/actuator/health || exit 1" ]
      interval: 20s
      timeout: 5s
      retries: 5
#    network_mode: "host"

  discovery-server:
    container_name: service-discovery
    stdin_open: true
    build:
      context: service-discovery
      dockerfile: Dockerfile
#      network: host
    ports:
      - 8761:8761
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:8761/actuator/health || exit 1" ]
      interval: 20s
      timeout: 5s
      retries: 5
    depends_on:
      config-server:
        condition: service_healthy
#    network_mode: "host"

  bootiful-java1:
    container_name: java-client1
    environment:
      - SPRING_PROFILES_ACTIVE=${BOOTIFUL_JAVA_PROFILE:-local}
      - CONFIG_SERVER=http://config-server:8888
      - EUREKA_SERVER=http://discovery-server:8761/eureka
    stdin_open: true
    build:
      context: bootiful-java
      dockerfile: Dockerfile
#      network: host
    ports:
      - ${BOOTIFUL_JAVA_PORT:-8007}:8007
    depends_on:
      discovery-server:
        condition: service_healthy
#    network_mode: "host"

  bootiful-java2:
    container_name: java-client2
    environment:
      - SPRING_PROFILES_ACTIVE=${BOOTIFUL_JAVA_PROFILE:-local}
      - CONFIG_SERVER=http://config-server:8888
      - EUREKA_SERVER=http://discovery-server:8761/eureka
    stdin_open: true
    build:
      context: bootiful-java
      dockerfile: Dockerfile
    #      network: host
    ports:
      - 8006:8007 # ${BOOTIFUL_JAVA_PORT:-8007}:8007
    depends_on:
      discovery-server:
        condition: service_healthy
  #    network_mode: "host"

  bootiful-kotlin:
    container_name: kotlin-client
    environment:
      - SPRING_PROFILES_ACTIVE=${BOOTIFUL_KOTLIN_PROFILE:-dev}
      - CONFIG_SERVER=http://config-server:8888
      - EUREKA_SERVER=http://discovery-server:8761/eureka
    stdin_open: true
    build:
      context: bootiful-kotlin
      dockerfile: Dockerfile
#      network: host
    ports:
      - 8008 # ${BOOTIFUL_KOTLIN_PORT:-8008}:8008
    depends_on:
      discovery-server:
        condition: service_healthy
#    network_mode: "host"