custom:
  message: '"Hello, I''m from bootiful-java.properties"'

server:
  port: 8007

spring:
  cloud:
    config:
      # override the remote properties with their own System properties or config files
      allowOverride: true
      # override from any local property source.
      overrideNone: true

# register to eureka server
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
    healthcheck:
      enabled: true
