server:
  port: 8888

#
# follow up https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#_pattern_matching_and_multiple_repositories
#
# - uri: config 저장소
# - searchPaths
#   config-client 를 추가하면서 config-repo 에 추가한 디렉토리를 아래 추가해야지 검색 가능
#   더 좋은 방법이 있을 수 있음. (위 주소 참고)
#
spring:
  application:
    name: configuration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/meowpunch/spring-cloud-msa.git
          default-label: main
          search-paths: 'repository/*'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
