# follow up Spring Cloud Config 3.0.3 doc
# https://docs.spring.io/spring-cloud-config/docs/3.0.3/reference/html/
server:
  port: 0

# default `application`
#spring:
#  application:
#    name: bootiful-kotlin

# default `http:localhost:8888`
#  config:
#    import: optional:configserver:${CONFIG_SERVER:http://localhost:8888}

# Spring Boot Actuator 에서 endpoint 중 config 를 재설정하는 endpoint `/actuator/refresh` 만 열어둔다.
#management.endpoints.jmx.exposure.exclude=*
#management.endpoints.web.base-path=/actuator
#management.endpoints.web.exposure.include=refresh


