custom:
  message: "Hello, I'm from application.yml of bootiful-java"

server:
  port: 0

# Spring Boot Actuator 에서 endpoint 중 config 를 재설정하는 endpoint `/actuator/refresh` 만 열어둔다.
management:
  endpoints:
    #    jmx.exposure.exclude: *
    web:
      #      base-path: '/refresh'
      exposure:
        include: refresh

# register to eureka server
eureka:
  client:
    serviceUrl.defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
    healthcheck.enabled: true
  instance.prefer-ip-address: true


#
## copied from hubble-api.properties
#
#db.host=192.168.0.30
#db.target=hubble2ops
#db.port=5432
#
#spring.datasource.driver-class-name=org.postgresql.Driver
##spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#spring.datasource.url=jdbc:postgresql://${db.host}:${db.port}/${db.target}?charSet=UTF-8&prepareThreshold=5
##spring.datasource.url=jdbc:log4jdbc:postgresql://${db.host}:${db.port}/${db.target}?charSet=UTF-8&prepareThreshold=5
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.hikari.maximum-pool-size=15